import React from 'react';
import {AbsoluteFill,Audio,Easing,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import data from './scenes.json';
import cues from './cues.json';

type Scene=(typeof data.scenes)[number];
const C={bg:'#07111f',panel:'#0d1b2a',text:'#f8fafc',muted:'#9eb1c6',cyan:'#67e8f9',blue:'#60a5fa',violet:'#a78bfa',green:'#6ee7b7',amber:'#fbbf77',line:'#28435f'};
const Card=({title,sub,accent=C.cyan,width=300}:{title:string;sub?:string;accent?:string;width?:number})=><div style={{width,minHeight:118,padding:'22px 24px',borderRadius:24,border:`1px solid ${accent}66`,background:'rgba(13,27,42,.94)',boxShadow:`0 0 44px ${accent}14`,display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontSize:28,fontWeight:800}}>{title}</div>{sub?<div style={{fontSize:19,color:C.muted,marginTop:8,lineHeight:1.4}}>{sub}</div>:null}</div>;
const Arrow=()=> <div style={{fontSize:42,color:C.cyan}}>→</div>;
const Chip=({children,accent=C.blue}:{children:React.ReactNode;accent?:string})=><div style={{padding:'10px 15px',borderRadius:999,border:`1px solid ${accent}55`,background:`${accent}12`,fontSize:19}}>{children}</div>;

const Overview=()=> <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:30,width:'100%'}}><div style={{display:'flex',alignItems:'center',gap:22}}><Card title="Agent Skill for ChatGPT" sub="SKILL.md 是核心入口" accent={C.cyan} width={390}/><Arrow/><Card title="Codebase → Explainer Video" sub="用户只需提供本地项目或 GitHub 地址" accent={C.green} width={430}/></div><div style={{display:'flex',gap:18}}><Card title="references/" sub="分析与制作规范" accent={C.blue} width={250}/><Card title="scripts/" sub="确定性辅助工具" accent={C.violet} width={250}/><Card title="assets/" sub="Remotion / Actions 模板" accent={C.amber} width={280}/></div></div>;
const Analysis=()=> <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:24,width:'100%',maxWidth:1260}}>{[
['scan_codebase.py','确定性仓库清单 · 跳过依赖、缓存、敏感文件',C.cyan],['project-manifest.json','技术栈 / 包管理器 / 入口线索',C.blue],['project-analysis.json','模块、外部系统、真实执行路径、风险',C.violet],['architecture.mmd','把验证过的关系压缩成可视化心智模型',C.green]
].map(([a,b,d])=><Card key={String(a)} title={String(a)} sub={String(b)} accent={String(d)} width={600}/>)}</div>;
const TTS=()=> <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:34}}><div style={{display:'flex',alignItems:'center',gap:18}}><Card title="1 scene = 1 TTS request" sub="避免一句一句拼接造成机械停顿" accent={C.violet}/><Arrow/><Card title="SentenceBoundary" sub="真实 offset + duration" accent={C.amber}/><Arrow/><Card title="Exact subtitles.srt" sub="不再按字符数估时间" accent={C.green}/></div><div style={{display:'flex',gap:14}}><Chip>narration.mp3</Chip><Chip accent={C.violet}>timings.json</Chip><Chip accent={C.amber}>storyboard.timed.json</Chip><Chip accent={C.green}>subtitles.srt</Chip></div></div>;
const Render=()=> <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:28}}><div style={{display:'flex',alignItems:'center',gap:18}}><Card title="Local Remotion" sub="npm + browser runtime"/><Arrow/><div style={{fontSize:30,color:C.muted}}>失败？</div><Arrow/><Card title="prepare_remotion_job.py" sub="打包成可移植 render job" accent={C.violet}/><Arrow/><Card title="GitHub Actions" sub="真实 remotion render" accent={C.green}/></div><div style={{fontSize:27,color:C.muted}}>typecheck → preview still → remotion render → ffprobe → artifact</div></div>;
const QA=()=> <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:22,width:'100%'}}>{[
['Audio','旁白总时长'],['Subtitle tail','最后一条字幕结束'],['Video','最终 MP4 时长'],['Manual sample','开头 · 中段 · 结尾']
].map(([a,b],i)=><Card key={a} title={a} sub={b} accent={[C.cyan,C.violet,C.amber,C.green][i]} width={300}/>)}</div>;
const Recap=()=> <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:32,width:'100%'}}><Card title="Codebase Video Explainer" sub="Agent Skill for ChatGPT" accent={C.cyan} width={520}/><div style={{display:'flex',alignItems:'center',gap:14}}>{['SKILL.md','references','scripts','assets'].map((x,i)=><React.Fragment key={x}><Card title={x} sub={['核心行为入口','分析 / 分镜 / 制作规范','确定性工具','Remotion / Actions 模板'][i]} accent={[C.cyan,C.blue,C.violet,C.amber][i]} width={250}/>{i<3?<Arrow/>:null}</React.Fragment>)}</div><div style={{fontSize:26,color:C.muted}}>“视频编译流水线”是工作方式，不是项目定位</div></div>;
const Visual=({scene}:{scene:Scene})=>scene.kind==='analysis'?<Analysis/>:scene.kind==='tts'?<TTS/>:scene.kind==='render'?<Render/>:scene.kind==='qa'?<QA/>:scene.kind==='recap'?<Recap/>:<Overview/>;
const Caption=({time}:{time:number})=>{const cue=[...cues].reverse().find(c=>time>=c.start&&time<=c.end+0.06); if(!cue)return null; return <div style={{position:'absolute',left:190,right:190,bottom:56,display:'flex',justifyContent:'center'}}><div style={{maxWidth:1480,padding:'14px 26px 16px',borderRadius:18,background:'rgba(0,0,0,.72)',fontSize:33,lineHeight:1.36,fontWeight:650,textAlign:'center',textShadow:'0 2px 6px #000'}}>{cue.text}</div></div>};
export const HomepageVideo=()=>{const frame=useCurrentFrame(); const {fps,durationInFrames}=useVideoConfig(); const time=frame/fps; const idx=data.scenes.findIndex(s=>time>=s.start&&time<s.end); const scene=data.scenes[idx<0?data.scenes.length-1:idx]; const lf=Math.max(0,Math.round((time-scene.start)*fps)); const enter=spring({frame:lf,fps,config:{damping:18,stiffness:110,mass:.9}}); const fade=interpolate(time,[scene.end-.4,scene.end],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.ease)}); const progress=frame/Math.max(1,durationInFrames-1); return <AbsoluteFill style={{background:C.bg,color:C.text,fontFamily:'"Noto Sans CJK SC","Microsoft YaHei","PingFang SC",system-ui,sans-serif'}}><Audio src={staticFile('narration.mp3')}/><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(rgba(103,232,249,.045) 1px, transparent 1px), linear-gradient(90deg, rgba(103,232,249,.045) 1px, transparent 1px)',backgroundSize:'54px 54px'}}/><div style={{position:'absolute',width:820,height:820,borderRadius:999,right:-220,top:-300,background:'radial-gradient(circle, rgba(96,165,250,.12), transparent 68%)'}}/><div style={{position:'absolute',left:0,top:0,height:6,width:`${progress*100}%`,background:`linear-gradient(90deg,${C.cyan},${C.violet})`}}/><div style={{position:'absolute',left:96,right:96,top:68,bottom:152,display:'flex',flexDirection:'column',opacity:enter*fade,transform:`translateY(${interpolate(enter,[0,1],[26,0])}px)`}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontSize:22,letterSpacing:2.3,color:C.cyan,fontWeight:800}}>{scene.kicker}</div><div style={{fontSize:21,color:C.muted}}>CODEBASE VIDEO EXPLAINER · {String(scene.index+1).padStart(2,'0')} / 06</div></div><div style={{fontSize:62,fontWeight:850,lineHeight:1.12,marginTop:16,letterSpacing:-1.4}}>{scene.title}</div><div style={{fontSize:25,color:C.muted,marginTop:13}}>{scene.subtitle}</div><div style={{flex:1,display:'flex',alignItems:'center',justifyContent:'center',marginTop:20}}><Visual scene={scene}/></div><div style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><span style={{fontSize:17,color:C.muted,marginRight:4}}>EVIDENCE</span>{scene.evidence.map(e=><span key={e} style={{fontSize:17,color:'#cbd5e1',border:`1px solid ${C.line}`,borderRadius:10,padding:'7px 10px',background:'rgba(13,27,42,.72)'}}>{e}</span>)}</div></div><Caption time={time}/></AbsoluteFill>};
